/**
 * Browser-side Web Push helpers — the client half of the notification channel.
 *
 * The flow these power: ask the user for notification permission, ask the
 * service worker (public/sw.js) to create a push subscription against this
 * app's VAPID key, then POST that subscription to /api/push/subscribe so the
 * server can reach this browser while the tab is closed.
 *
 * Client-side only — no server imports here; this file is pulled into browser
 * bundles. Nothing throws: a denied permission, an unsupported browser, or a
 * failed registration degrades to a null return, and the caller treats push
 * as an optional enhancement (the in-app bell over REST/sockets is the base
 * experience).
 */

/**
 * Converts the VAPID public key (base64url, as generated by `web-push
 * generate-vapid-keys`) into the Uint8Array the Push API expects for
 * `applicationServerKey`. The padding restore is the standard recipe: Node's
 * base64url output drops trailing "=", but atob requires it.
 */
export function urlBase64ToUint8Array(base64: string): Uint8Array<ArrayBuffer> {
  const padding = "=".repeat((4 - (base64.length % 4)) % 4);
  const base64Full = (base64 + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64Full);
  // Constructed from an explicit ArrayBuffer (not `new Uint8Array(length)`)
  // so the type is Uint8Array<ArrayBuffer> — pushManager.subscribe's
  // BufferSource parameter rejects the looser ArrayBufferLike on current
  // TypeScript lib definitions.
  const output = new Uint8Array(new ArrayBuffer(raw.length));
  for (let i = 0; i < raw.length; i++) {
    output[i] = raw.charCodeAt(i);
  }
  return output;
}

/**
 * Fetches the VAPID public key from /api/push/public-key. Empty string means
 * push is not configured server-side — subscribeToPush checks for that and
 * bows out before ever prompting the user for permission.
 */
export async function getVapidPublicKey(): Promise<string> {
  try {
    const res = await fetch("/api/push/public-key");
    if (!res.ok) return "";
    const data = (await res.json()) as { publicKey?: string };
    return typeof data.publicKey === "string" ? data.publicKey : "";
  } catch {
    return "";
  }
}

/**
 * The full opt-in: permission → subscription → registration on the server.
 * Returns the browser PushSubscription on success, or null when the user
 * denied permission, the browser has no service worker/push support, the
 * server has no VAPID key, or anything in the chain failed — every failure is
 * "push is off", never a crash.
 */
export async function subscribeToPush(): Promise<PushSubscription | null> {
  // The Notification API only exists in a window context; SSR and non-browser
  // environments get the clean null rather than a ReferenceError.
  if (typeof window === "undefined" || !("Notification" in window)) {
    return null;
  }
  if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
    return null;
  }

  const publicKey = await getVapidPublicKey();
  if (!publicKey) return null;

  const permission = await Notification.requestPermission();
  if (permission !== "granted") return null;

  try {
    // Nothing registers sw.js elsewhere in the app, so it MUST happen here —
    // without a registration, serviceWorker.ready below never resolves and
    // the caller's button would hang on "Enabling…" forever. Register is
    // idempotent (a no-op when the worker is already active), so calling it
    // on every opt-in is free; ready then waits out activation.
    await navigator.serviceWorker.register("/sw.js");
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.subscribe({
      // Chrome requires this: every push must show a visible notification,
      // which sw.js's `push` handler does.
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(publicKey),
    });

    // toJSON() gives the plain { endpoint, keys: { p256dh, auth } } shape the
    // API route validates; a bare structured-clone of the subscription object
    // can carry extra fields.
    const res = await fetch("/api/push/subscribe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(subscription.toJSON()),
    });
    if (!res.ok) return null;

    return subscription;
  } catch {
    // subscribe() throws if permission was revoked mid-flow or the browser
    // rejected the applicationServerKey; fetch throws if the network dropped.
    // Either way push is simply not on for this session.
    return null;
  }
}
